# Netlify configuration for LitmusAI
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

# Build environment
[build.environment]
  NODE_VERSION = "18"
  # Disable Python build detection
  PYTHON_VERSION = ""
  # Disable secrets scanning (secrets are in environment variables, not in code)
  SECRETS_SCAN_ENABLED = "false"

# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/billing/config"
  to = "/.netlify/functions/billing-config"
  status = 200

[[redirects]]
  from = "/api/billing/checkout-session"
  to = "/.netlify/functions/checkout-session"
  status = 200

[[redirects]]
  from = "/api/billing/customer-portal"
  to = "/.netlify/functions/customer-portal"
  status = 200

[[redirects]]
  from = "/api/billing/subscription-status"
  to = "/.netlify/functions/subscription-status"
  status = 200

[[redirects]]
  from = "/api/webhooks/stripe"
  to = "/.netlify/functions/stripe-webhook"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
