services:
  - type: web
    name: litmusai-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && cd backend && flask db upgrade"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: litmusai-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://litmusai.netlify.app
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: "10000"

databases:
  - name: litmusai-db
    databaseName: litmusai
    user: litmusai
    plan: free
