#!/usr/bin/env python3
"""Generate a focused Supabase recovery SQL script from a cluster backup dump.

This extractor keeps only the auth/public user COPY blocks needed for login and
billing profile continuity:
- COPY auth.users
- COPY auth.identities
- COPY public.users

It also normalizes common tier typos in public.users.subscription_tier.
"""

from __future__ import annotations

import argparse
import gzip
import re
from pathlib import Path

TABLES = ('auth.users', 'auth.identities', 'public.users')


def _read_dump(path: Path) -> str:
    if path.suffix == '.gz':
        with gzip.open(path, 'rt', encoding='utf-8', errors='ignore') as handle:
            return handle.read()
    return path.read_text(encoding='utf-8', errors='ignore')


def _extract_copy_block(dump_text: str, table_name: str) -> str:
    pattern = rf"(COPY {re.escape(table_name)} \([^\n]+\) FROM stdin;\n(?:.*?\n)\\\.)"
    match = re.search(pattern, dump_text, flags=re.S)
    if not match:
        raise RuntimeError(f'Could not find COPY block for {table_name}')
    return match.group(1)


def _normalize_tier(value: str) -> str:
    lowered = value.strip().lower()
    if lowered in ('preminum', 'professional'):
        return 'premium'
    return value


def _normalize_public_users_block(copy_block: str) -> str:
    lines = copy_block.splitlines()
    if len(lines) < 2:
        return copy_block

    header = lines[0]
    row_lines = lines[1:-1]
    terminator = lines[-1]

    columns_match = re.search(r'COPY public\.users \(([^\)]+)\) FROM stdin;', header)
    if not columns_match:
        return copy_block

    columns = [col.strip() for col in columns_match.group(1).split(',')]
    try:
        tier_idx = columns.index('subscription_tier')
    except ValueError:
        return copy_block

    normalized_rows = []
    for row in row_lines:
        if not row.strip() or row.strip() == '\\.' or row.strip().startswith('--'):
            continue

        parts = row.split('\t')
        if tier_idx < len(parts) and parts[tier_idx] not in ('', '\\N'):
            parts[tier_idx] = _normalize_tier(parts[tier_idx])
        normalized_rows.append('\t'.join(parts))

    rebuilt = [header, *normalized_rows, terminator]
    return '\n'.join(rebuilt)


def _build_recovery_sql(auth_users_block: str, identities_block: str, public_users_block: str) -> str:
    return f"""-- Generated by scripts/extract_supabase_recovery_sql.py
-- Purpose: restore user login identities and app billing profile data only.

BEGIN;

DO $$
BEGIN
  IF to_regclass('auth.users') IS NULL THEN
    RAISE EXCEPTION 'Missing target table auth.users';
  END IF;
  IF to_regclass('auth.identities') IS NULL THEN
    RAISE EXCEPTION 'Missing target table auth.identities';
  END IF;
  IF to_regclass('public.users') IS NULL THEN
    RAISE EXCEPTION 'Missing target table public.users';
  END IF;
END $$;

{auth_users_block}

{identities_block}

{public_users_block}

DO $$
DECLARE
  imported_auth_count integer;
  imported_public_count integer;
  mismatched_count integer;
BEGIN
  SELECT COUNT(*) INTO imported_auth_count FROM auth.users;
  SELECT COUNT(*) INTO imported_public_count FROM public.users;

  IF imported_auth_count = 0 THEN
    RAISE EXCEPTION 'No rows found in auth.users after restore';
  END IF;

  IF imported_public_count = 0 THEN
    RAISE EXCEPTION 'No rows found in public.users after restore';
  END IF;

  SELECT COUNT(*) INTO mismatched_count
  FROM public.users pu
  LEFT JOIN auth.users au ON au.id = pu.id
  WHERE au.id IS NULL;

  IF mismatched_count > 0 THEN
    RAISE EXCEPTION 'Detected % public.users rows without matching auth.users rows', mismatched_count;
  END IF;
END $$;

COMMIT;
"""


def main() -> int:
    parser = argparse.ArgumentParser(description='Extract user recovery SQL from a Supabase backup dump.')
    parser.add_argument('--input', required=True, help='Path to .backup or .backup.gz file')
    parser.add_argument('--output', required=True, help='Path to output .sql file')
    parser.add_argument('--overwrite', action='store_true', help='Overwrite output if it exists')
    args = parser.parse_args()

    input_path = Path(args.input).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()

    if not input_path.exists():
        raise FileNotFoundError(f'Input backup file not found: {input_path}')

    if output_path.exists() and not args.overwrite:
        raise FileExistsError(f'Output file already exists: {output_path}. Use --overwrite to replace it.')

    dump_text = _read_dump(input_path)

    auth_users_block = _extract_copy_block(dump_text, TABLES[0])
    identities_block = _extract_copy_block(dump_text, TABLES[1])
    public_users_block = _extract_copy_block(dump_text, TABLES[2])
    public_users_block = _normalize_public_users_block(public_users_block)

    sql = _build_recovery_sql(auth_users_block, identities_block, public_users_block)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(sql, encoding='utf-8')

    print(f'Wrote recovery SQL to: {output_path}')
    print('Included COPY blocks: auth.users, auth.identities, public.users')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
